const roles = [
  { company: "Micron Technology", title: "Equipment Technician", period: "2020 — Present · Singapore", points: ["Use advanced diagnostic equipment to perform system checks and support reliable manufacturing operations.", "Plan and execute preventive maintenance, including inspection, disassembly, and reassembly of manufacturing machinery.", "Maintain detailed equipment and maintenance records to inform future reliability strategies and ensure standards are met."] },
  { company: "GlobalFoundries", title: "Associate Engineering Intern · Yield Engineering", period: "Jul 2019 — Dec 2019 · Singapore", points: ["Supported recipes for defect-inspection tools and daily equipment recovery operations.", "Assisted engineering documentation and equipment-improvement work in a yield-focused environment."] },
  { company: "Marina Centre Holdings", title: "Assistant Officer Intern · Engineering & Security", period: "Mar 2018 — Aug 2018 · Singapore", points: ["Supported materials planning, pipe inspection, pumps replacement, and electrical troubleshooting.", "Updated building layouts using AutoCAD and supported lighting and CCTV-related installations."] },
];
const skillSets = [
  { no: "Pillar 01", title: "Equipment Reliability", items: ["Preventive maintenance planning", "System diagnostics & inspection", "Component repair & refurbishment", "Maintenance documentation"] },
  { no: "Pillar 02", title: "Operations Support", items: ["Equipment recovery workflows", "Tool and process documentation", "Technical coordination", "Uptime-minded execution"] },
  { no: "Pillar 03", title: "Engineering Foundations", items: ["Mechanical systems inspection", "Electrical troubleshooting", "AutoCAD layout updates", "Facilities & security systems"] },
];

export default function Home() {
  return <main>
    <header className="masthead"><div className="shell masthead-inner"><div className="nameplate"><a href="#top">Pyae Thi La</a><span>Singapore · Equipment & Operations</span></div><nav aria-label="Primary navigation"><a href="#about">About</a><a href="#journey">Career Timeline</a><a href="#capabilities">Capabilities</a><a href="#portfolio">Case Notes</a><a className="outlined-link" href="https://www.linkedin.com/in/pyae-thi-la-08827b179" target="_blank" rel="noreferrer">LinkedIn ↗</a></nav></div></header>
    <div className="shell">
      <section id="top" className="hero"><div className="hero-main"><p className="eyebrow"><i /> Semiconductor Manufacturing · Equipment Operations</p><h1>Engineering reliability into demanding fabrication environments.</h1><p className="lead">A Singapore-based Equipment Technician focused on precise maintenance, systematic troubleshooting, and the operational discipline that keeps manufacturing equipment ready.</p><div className="actions"><a className="button dark" href="#journey">Read chronology ↓</a><a className="button light" href="https://www.linkedin.com/in/pyae-thi-la-08827b179" target="_blank" rel="noreferrer">LinkedIn profile ↗</a></div></div><aside className="profile-card"><img src="/pyae-thi-la.jpg" alt="Pyae Thi La" /><div className="profile-info"><span className="eyebrow">Professional Profile</span><h2>Pyae<br />Thi La</h2><p>Equipment Technician<br />Singapore</p></div><div className="profile-note">Focused on the systems, details, and decisions that protect uptime.</div></aside><dl className="metrics"><div><dt>EXPERIENCE ARC</dt><dd>6+ Years</dd><small>Equipment operations</small></div><div><dt>CURRENT ROLE</dt><dd>Micron</dd><small>Equipment Technician</small></div><div><dt>WORKING STYLE</dt><dd>Precise</dd><small>Maintenance & diagnostics</small></div><div><dt>BASE</dt><dd>Singapore</dd><small>Engineering operations</small></div></dl></section>
      <section id="about" className="about section"><div className="section-intro"><p className="eyebrow">Executive Profile</p><h2>Precision is not an aspiration. It is an operational standard.</h2></div><div className="about-copy"><p>My work combines hands-on equipment care with a clear focus on operational impact. I bring a methodical approach to preventive maintenance, fault diagnosis, and the detailed records that turn daily work into better long-term decisions.</p><p>From facilities engineering to semiconductor manufacturing, I have built practical experience across mechanical systems, inspection, technical documentation, and equipment improvement.</p><blockquote>“Reliable output begins long before a system is running—it starts with disciplined preparation, careful inspection, and respect for every detail.”</blockquote></div></section>
      <section id="journey" className="section journey"><div className="section-heading"><div><p className="eyebrow">Chronological Record</p><h2>Career Journey & Engagements</h2></div><p>Singapore Engineering Ecosystem</p></div><div className="roles">{roles.map((role) => <article className="role" key={role.company}><div><h3>{role.company}</h3><h4>{role.title}</h4><p className="period">{role.period}</p></div><ul>{role.points.map((point) => <li key={point}>{point}</li>)}</ul></article>)}</div></section>
      <section id="capabilities" className="section capabilities"><p className="eyebrow">Core Competencies</p><h2>Technical Matrix & Systematic Skills</h2><div className="skill-grid">{skillSets.map((set) => <article className="skill-card" key={set.no}><p className="eyebrow">{set.no}</p><h3>{set.title}</h3><ul>{set.items.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></section>
      <section id="portfolio" className="portfolio"><div><p className="eyebrow">Technical Notes</p><h2>Portfolio<br />in development.</h2><p>Selected work and case studies will be added here as the portfolio evolves.</p></div><a className="button dark" href="mailto:pyaethila1996@gmail.com">Start a conversation ↗</a></section>
    </div><footer><div className="shell footer-inner"><span>Pyae Thi La · Equipment Technician · Singapore</span><span>Editorial & Corporate Design System</span><span>© {new Date().getFullYear()} All rights reserved</span></div></footer>
  </main>;
}
